config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :articles

  resources :companies
  
  resources :user_roles

  resources :country do
    collection do
      get :country_select
    end
  end
  
  resources :state do
    collection do
      get :state_select
      get :user
    end
  end
  
  resources :city
  resources	:user_regions
  resources :regions
  resources :images
  resources :places
  resources :nodes
  

  get 'welcome/index'

  

  root 'welcome#index'
  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord
	
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
	 mount_uploader :image, ImageUploader
end

app/models/node.rb
class Node < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
	belongs_to :company
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader

 	validates_presence_of :first_name, :last_name

  belongs_to :company
  belongs_to :user_role

 	def name
 		"#{first_name} #{last_name}"
 	end

end

app/models/user_region.rb
class UserRegion < ApplicationRecord

	belongs_to :user
	belongs_to :region

end 

app/models/user_role.rb
class UserRole < ApplicationRecord
end

app/controllers/state_controller.rb
class StateController < ApplicationController
  
	def new
		
	end

  def index
  	@states = State.all
  end

  def create
  	@state = State.new(state_params)
  	if @state.save
  		redirect_to @state
		else
			render 'new'  		
  	end
  end
 
  def state_select
    @cities = CS.get(params[:country_code], params[:state_code])

    respond_to do |format|
      format.js {}
    end  
  end
  
  def show
  	@state = State.find(params[:id])
  end

  def edit
  	@state = State.find(params[:id])
  end

  def update
  	@state = State.find(params[:id])
  	if @state.update(state_params)
  		redirect_to @state
		else
			render 'edit'  		
  	end
  end

  def destroy
  	@state = State.find(params[:id])
  	@state.destroy
  	redirect_to state_index_path
  end

  def user
  end

  private
  def state_params
  	params.require(:state).permit(:state_name, :country_code)
  end
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/country_helper.rb
module CountryHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/state_helper.rb
module StateHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/state/_state_select.html.erb
<%= select_tag "state[state_name]", options_from_collection_for_select(@states, :first, :last), class: "form-control" %>


<script type="text/javascript">
	
	$('#state_state_name').change(function(){
		var value = this.value;
		var country_code = $("#company_country_id").val();
		$.ajax({
			url: "/state/state_select",
			type: "GET",
			data: {state_code: value, country_code: country_code},
		})
	});
</script>

app/views/state/edit.html.erb
<div class="d-flex justify-content-center"><h1>Edit State</h1></div><br>
<%= form_with(model: @state,local: true)  do |f| %>
	
	<div class="form-group d-flex justify-content-center">
			<%= f.label :state_name, "State name:", class: "control-label col-md-3"%>
			<%= f.text_field :state_name, class: "form-control col-md-8" %>
	</div>

	<div class="offset-md-5">
			<%= f.submit "Save", class: "btn btn-primary" %>
			<%= f.submit "Cancel", class: "btn btn-info" %>
			<%= link_to 'Back' , state_index_path, class: " btn btn-success"%>
	</div>
<% end %>

app/views/state/index.html.erb
<div class="d-flex justify-content-center"><h1>List of States</h1></div><br>

<table class="table table-striped table-dark table-bordered">
	<thead>
		<tr>
			<th>State Name</th>
		</tr>
	</thead>
	<tbody>
		<% @states.each  do |state|%>
		<tr>
			<td><%= state.state_name %></td>
			<td><%= link_to 'Show',  state_path(state) %></td>
			<td><%= link_to 'Edit', edit_state_path(state) %></td>
			<td><%= link_to 'Delete',  state_path(state), method: :delete, data: {confirm: 'Are You Sure'} %></td>
		</tr>
		<div>
		</div>
		<% end %>
	</tbody>
</table>

app/views/state/new.html.erb
<div class="d-flex justify-content-center"><h1>Create State</h1></div><br>
<%= form_with scope: :state, url: state_index_path,	local: true  do |f| %>
	<div class="form-group col-md-4">
		<%= f.label :Country %>
		<%= f.select :country_code, collection: CountryStateSelect.countries_collection, :class=> 'form-control'%>
	</div>


	<div class="form-group d-flex justify-content-center">
		<%= f.label :state_name, "State name:", class: "control-label col-md-3"%>
		<%= f.text_field :state_name, class: "form-control col-md-8" %>
	</div>

	<div class="offset-md-5">
		<%= f.submit "Save", class: "btn btn-primary" %>
		<%= f.submit "Cancel", class: "btn btn-info" %>
		<%= link_to 'Back' , state_index_path, class: " btn btn-success"%>
	</div>
<% end %>

app/views/state/show.html.erb
<div class="d-flex justify-content-center"><h1>Show Country</h1></div><br>
<p>
	<strong>State name:</strong>
	<%= @state.state_name %>
</p>

<div>
	<%= link_to 'Back' , state_index_path, :class=> "btn btn-outline-danger"%>
</div>

app/views/state/state_select.js.erb
$('.city-select-box').html("<%= escape_javascript(render partial: 'city/city_select') %>");

app/views/state/user.html.erb
<div class="d-flex justify-content-center"><h1>Details of Users</h1></div><br>

<table class="table table-striped table-dark table-bordered">
	<thead>
		<tr>
			<th>Email</th>
			<th>Name</th>
			<th>Company name</th>
			<th>Role</th>
			<th>Start Date</th>
			<th>End Date</th>
			<th>Monthly Charge</th>
			<th>Image</th>
			<th>Active</th>
		</tr>
	</thead>
	<tbody>
		
		<tr>
			<td><%= current_user.email %></td>
			<td><%=	current_user.name %></td>
			<td><%=	current_user.company.try(:name) %></td>
			<td><%= current_user.user_role.try(:role_name) %></td>
			<td><%=	current_user.start_date %></td>
			<td><%= current_user.end_date %></td>
			<td><%= current_user.monthly_charge %></td>
			<td><%= image_tag current_user.image_url.to_s , :size => "260x180" %></td>
			<td><%= current_user.active %></td>
			</td>
		</tr>
		<div>
		</div>
		
	</tbody>
</table>