config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :articles

  resources :companies
  
  resources :user_roles

  resources :country do
    collection do
      get :country_select
    end
  end
  
  resources :state do
    collection do
      get :state_select
      get :user
    end
  end
  
  resources :city
  resources	:user_regions
  resources :regions
  resources :images
  resources :places
  resources :nodes
  

  get 'welcome/index'

  

  root 'welcome#index'
  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord
	
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
	 mount_uploader :image, ImageUploader
end

app/models/node.rb
class Node < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
	belongs_to :company
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader

 	validates_presence_of :first_name, :last_name

  belongs_to :company
  belongs_to :user_role

 	def name
 		"#{first_name} #{last_name}"
 	end

end

app/models/user_region.rb
class UserRegion < ApplicationRecord

	belongs_to :user
	belongs_to :region

end 

app/models/user_role.rb
class UserRole < ApplicationRecord
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	def new
		
	end

	def index
		@companies = Company.all	
	end

	def create
		# byebug
		city = params[:city][:city_name]
		state = params[:state][:state_name]
		@company = Company.new(company_params)
		if @company.save!
			redirect_to @company
		else
			render 'new'
		end
		@company.update(city_id: city, state_id: state )
	end

	def show
		@company = Company.find(params[:id])
	end

	def edit
		@company = Company.find(params[:id])
	end

	def update
		@company = Company.find(params[:id])
		if @company.update(company_params)
			redirect_to @company
		else
			render 'edit'
		end
	end

	def destroy
		@company = Company.find(params[:id])
		@company.destroy

		redirect_to companies_path
	end

	private 
	def company_params
		params.require(:company).permit(:name, :country_id,:state_id, :city_id, :postcode, :startdate,:active)
	end
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/country_helper.rb
module CountryHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/state_helper.rb
module StateHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/edit.html.erb
<div class="d-flex justify-content-center"><h1>Edit Company</h1></div><br>

<%= form_with(model: @company, local: true) do |f| %>
	<div class="container">

			<div class="form-group">
				<%= f.label :CompanyName, :class=> "col-sm-2 col-form-label" %>
				<div class="col-sm-8">
				<%= f.select :company_id, Company.all.map {|c| [ c.name]}, {promt:"Select"}, class: "form-control" %>
				</div> 
			</div>
			
			
			<div class="form-group">
				<%= f.label :Country, :class=> "col-sm-2 col-form-label" %>
				<div class="col-sm-8">
					<%= f.select(:country_id, CS.countries.invert, {}, {id: "company_country_id", class: 'form-control'}) %>
				</div>
			</div>

			<div class="form-group">
				<%= f.label :State, :class=> "col-sm-2 col-form-label" %>
				<div class="col-sm-8 state-select-box">
					<%= f.select(:state_id, options_for_select([]), {}, {class: 'form-control'}) %>
				</div>
			</div>

			<div class="form-group">
				<%= f.label :City, :class=> "col-sm-2 col-form-label" %>
				<div class="col-sm-8 city-select-box">
					<%= f.select(:city_id, options_for_select([]), {}, {class: 'form-control'}) %>
				</div>
			</div>

			<div class="form-group">
				<%= f.label :Postcode, :class=> "col-sm-2 col-form-label" %>
				<div class="col-sm-8">
					<%= f.text_field :postcode, :class=> "form-control", :placeholder=>"Postcode" %>
				</div>
			</div>

			<div class="form-group">
				<%= f.label :StartDate, :class=>'col-sm-2 col-form-label' %>
				<div class="col-sm-8"  >
						<%= f.text_field :startdate, :class=>'form-control myDatePicker', autocomplete: :off %>
						<span class="input-group-addon ">
								<span class="glyphicon glyphicon-calendar "></span>
						</span>
				</div>
			</div>
			

   		<div class="form-group">
				<div class="form-check">
					<%= f.check_box :active%>
					<%= f.label :Active %>
				</div>
			</div>
			
			<div class="btn-group col-md-4 offset-md-3 btn  btn-group-lg">
				<%= link_to 'Back' , companies_path, class: "btn btn-info btn-outline-success  " %>
				<%= f.submit "Save", class: "btn btn-info " %>
  		</div>
	</div>



		<script type="text/javascript">
	    $(document).ready(function(){
		    $('.myDatePicker').datepicker({
		    	format: 'yyyy/mm/dd',
		    	autoclose: true
		    });
		  });

			$('#company_country_id').change(function(){
				var value = this.value ;
			  	$.ajax({
			    	url: "/country/country_select",
			    	type: "GET",
			    	data: {country_code: value },
			  	})
			});
		</script>

<% end %>

































	<!-- <div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
					<%#= f.label :CompanyName, :class=> "col-sm-2 col-form-label"%>
				<div class="col-sm-8">
					<%#= f.text_field :name, :class => "form-control", :placeholder=> "Company" %>
				</div>
			</div>
		</div><br><br><br>
		
		<div class="form-row col-md-12">
			<div class="form-group col-md-4">
				<%#= f.label :Country %>
				<%#= f.select :country_id,[["Apple", 1], ["Grape", 2]], { class: "selectpicker" },:class=>"form-control" %>
			</div>

			<div class="form-group col-md-4">
				<%#= f.label :State %>
				<%#= f.select :state_id,[["Apple", 1], ["Grape", 2]], { class: "selectpicker" },:class=>"form-control" %>
			</div>

			<div class="form-group col-md-4">
				<%#= f.label :City %>
				<%#= f.select :city_id,[["Apple", 1], ["Grape", 2]], { class: "selectpicker" },:class=>"form-control" %>
			</div>
		</div>

		<div class="col-md-12 form-inline">
			<div class="form-group">
					<%#= f.label :Postcode, :class=> "col-sm-2 col-form-labe" %>
				<div class="col-sm-10">
					<%#= f.text_field :postcode, :class=> "form-control", :placeholder=>"Postcode" %>
				</div>
			</div>

      <div class='col-sm-6'>
          <div class="form-group">
          		<%#= f.label :StartDate, :class=> "col-form-labe" %>
            	<div class='input-group date' id='datepicker1'>
              	<%#= f.text_field :startdate, :class=>"datepicker" %>
                  <span class="input-group-addon">
                      <span class="glyphicon glyphicon-calendar"></span>
                  </span>
              </div>
          </div>
      </div>
     	<script type="text/javascript">
			  $(document).ready(function(){
			    $('.datepicker').datepicker();
			  });
		</script>

			<div class="form-group">
					<div class="form-check">
						<%#= f.check_box :active%>
						<%#= f.label :Active %>
					</div>
			</div>
		</div><br><br><br>
				<div class="col-md-4 offset-md-3 btn btn-info">
					<%#= link_to 'Back' , companies_path%>
				</div>
				<div class="offset-md-2">
					<%#= f.submit "Save", class: "btn btn-outline-success" %>
					<%#= f.submit "Cancel", class: "btn btn-outline-warning" %>
				</div>
				
	</div>
</div> -->

app/views/companies/index.html.erb
<div class="d-flex justify-content-center"><h1>List of Companies</h1></div><br>

<table class="table table-striped table-dark table-bordered">
	<thead>
		<tr>
			<th>Name</th>
			<th>Country Id</th>
			<th>State Id</th>
			<th>City Id</th>
			<th>Post Code</th>
			<th>Start Date</th>
			<th>Active</th>
			<th>
				<%= link_to 'Back' , new_company_path, :class=> "btn btn-outline-info"%>
			</th>
			
		</tr>
	</thead>
	<tbody>
		<% @companies.each  do |c|%>
		<tr>
			<td><%= c.name %></td>
			<td><%= c.country_id %></td>
			<td><%= c.state_id %></td>
			<td><%= c.city_id %></td>
			<td><%= c.postcode %></td>
			<td><%= c.startdate %></td>
			<td><%= c.active %></td>
			<td><%= link_to 'Show',  company_path(c) %></td>
			<td><%= link_to 'Edit', edit_company_path(c) %></td>
			<td><%= link_to 'Delete',  company_path(c), method: :delete, data: {confirm: 'Are You Sure'} %></td>
		</tr>
		<div>
		</div>
		<% end %>
	</tbody>
</table>

app/views/companies/new.html.erb
<div class="d-flex justify-content-center"><h1>Add company</h1></div><br>


<%= form_with scope: :company, url: companies_path, local: true do |f|%>
	<div class="container">

			<div class="form-group">
				<%= f.label :CompanyName, :class=> "col-sm-2 col-form-label" %>
				<div class="col-sm-8">
				<%= f.text_field :name, class: "form-control" %>
				</div> 
			</div>
			
			
			<div class="form-group">
				<%= f.label :Country, :class=> "col-sm-2 col-form-label" %>
				<div class="col-sm-8">
					<%= f.select(:country_id, CS.countries.invert, {}, {id: "company_country_id", class: 'form-control'}) %>
				</div>
			</div>

			<div class="form-group">
				<%= f.label :State, :class=> "col-sm-2 col-form-label" %>
				<div class="col-sm-8 state-select-box">
					<%= f.select(:state_id, options_for_select([]), {}, {class: 'form-control'}) %>
				</div>
			</div>

			<div class="form-group">
				<%= f.label :City, :class=> "col-sm-2 col-form-label" %>
				<div class="col-sm-8 city-select-box">
					<%= f.select(:city_id, options_for_select([]), {}, {class: 'form-control'}) %>
				</div>
			</div>

			<div class="form-group">
				<%= f.label :Postcode, :class=> "col-sm-2 col-form-label" %>
				<div class="col-sm-8">
					<%= f.text_field :postcode, :class=> "form-control", :placeholder=>"Postcode" %>
				</div>
			</div>

			<div class="form-group">
				<%= f.label :StartDate, :class=>'col-sm-2 col-form-label' %>
				<div class="col-sm-8"  >
						<%= f.text_field :startdate, :class=>'form-control myDatePicker', autocomplete: :off %>
						<span class="input-group-addon ">
								<span class="glyphicon glyphicon-calendar "></span>
						</span>
				</div>
			</div>
			

     <!--  <div class="form-group">
    		<%#= f.label :StartDate, :class=> "col-sm-2 col-form-label" %>
      	<div class='col-sm-8' id='datepicker1'>
        	<%#= f.text_field :startdate, :class=> "form-control", autocomplete: :off %>
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div> -->
	      	

			<div class="form-group">
				<div class="form-check">
					<%= f.check_box :active%>
					<%= f.label :Active %>
				</div>
			</div>
			
			<div class="btn-group col-md-4 offset-md-3 btn  btn-group-lg">
				<%= link_to 'Back' , companies_path, class: "btn btn-info btn-outline-success  " %>
				<%= f.submit "Save", class: "btn btn-info " %>
  		</div>
					
	</div>

<% end %>

<script type="text/javascript">
    $(document).ready(function(){
	    $('.myDatePicker').datepicker({
	    	format: 'yyyy/mm/dd',
	    	autoclose: true
	    });
	  });

	$('#company_country_id').change(function(){
		var value = this.value ;
	  	$.ajax({
	    	url: "/country/country_select",
	    	type: "GET",
	    	data: {country_code: value },
	  	})
	});


	
</script>

app/views/companies/show.html.erb
	<div class="d-flex justify-content-center"><h1>Show Comapny</h1></div><br>

<p>
	<strong>Name:</strong>
	<%= @company.name %>
</p>
<p>
	<strong>Country_id:</strong>
	<%= @company.country_id %>

</p>
<p>
	<strong>State_id:</strong>
	<%= @company.state_id %>
</p>
<p>
	<strong>City_id:</strong>
	<%= @company.city_id %>
</p>
<p>
	<strong>Postcode:</strong>
	<%= @company.postcode %>
</p>
<p>
	<strong>StartDate:</strong>
	<%= @company.startdate %>
</p>
<p>
	<strong>Active:</strong>
	<%= @company.active %>
</p>
<div>
	<%= link_to 'Back' , companies_path, :class=> "btn btn-outline-danger"%>
</div>