config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :articles

  resources :companies
  
  resources :user_roles

  resources :country do
    collection do
      get :country_select
    end
  end
  
  resources :state do
    collection do
      get :state_select
      get :user
    end
  end
  
  resources :city
  resources	:user_regions
  resources :regions
  resources :images
  resources :places
  resources :nodes
  

  get 'welcome/index'

  

  root 'welcome#index'
  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord
	
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
	 mount_uploader :image, ImageUploader
end

app/models/node.rb
class Node < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
	belongs_to :company
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader

 	validates_presence_of :first_name, :last_name

  belongs_to :company
  belongs_to :user_role

 	def name
 		"#{first_name} #{last_name}"
 	end

end

app/models/user_region.rb
class UserRegion < ApplicationRecord

	belongs_to :user
	belongs_to :region

end 

app/models/user_role.rb
class UserRole < ApplicationRecord
end

app/controllers/user_regions_controller.rb
class UserRegionsController < ApplicationController

	def new
		
	end

	def index
		@user_regions = UserRegion.all
	end

	def create
		@user_region = UserRegion.new(user_region_params)
		if @user_region.save
			redirect_to @user_region
		else
			render 'new'
		end
	end

	def show
		@user_region = UserRegion.find(params[:id])
	end
	
	def edit
		@user_region = UserRegion.find(params[:id])
	end

	def update
		@user_region = UserRegion.find(params[:id])
		@user_region.update(user_region_params)

		redirect_to user_regions_path
	end

	def destroy
		@user_region = UserRegion.find(params[:id])
		@user_region.destroy

		redirect_to user_regions_path
	end

	private 
	def user_region_params
		params.require(:user_region ).permit(:user_id, :region_id)
	end
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/country_helper.rb
module CountryHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/state_helper.rb
module StateHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_regions_helper.rb
module UserRegionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user_regions/edit.html.erb
<div class="d-flex justify-content-center"><h1>Edit User Region</h1></div><br>
<%= form_with(model: @user_region, local: true)  do |f| %>
	
	<div class="form-group d-flex justify-content-center">
		<%= f.label :User , "User name:", class: "control-label col-md-3"%>
		<%= f.collection_select :user_id, User.all, :id, :first_name, {},{:class=>"form-control col-md-8"} %>
	</div>
	<div class="form-group d-flex justify-content-center">
		<%= f.label :Region , "Region:", class: "control-label col-md-3"%>
		<%= f.collection_select :region_id,Region.all, :id,:region_name, {}, {:class=>"form-control col-md-8"} %>
	</div>

	

	<div class="offset-md-5">
			<%= f.submit "Save", class: "btn btn-primary" %>
			<%= f.submit "Cancel", class: "btn btn-info" %>
			<%= link_to 'Back' ,  user_regions_path, class: " btn btn-success"%>
	</div>
<% end %>

app/views/user_regions/index.html.erb
<div class="d-flex justify-content-center"><h1>List of User and Region</h1></div><br>

<table class="table table-striped table-dark table-bordered">
	<thead>
		<tr>
			<th>User</th>
			<th>Region</th>
			<th>
				<%= link_to 'Back' ,new_user_region_path, :class=> "btn btn-outline-danger"%>
			</th>
		</tr>
	</thead>
	<tbody>
		<% @user_regions.each  do |ur|%>
		<tr>
			<td><%=  ur.user.name %></td>
			<td><%= ur.region.region_name %></td>
			<td><%= link_to 'Show',  user_region_path(ur) %></td>
			<td><%= link_to 'Edit',  edit_user_region_path(ur) %></td>
			<td><%= link_to 'Delete',  user_region_path(ur), method: :delete, data: {confirm: 'Are You Sure'} %></td>
		</tr>
		<div>
		</div>
		<% end %>
	</tbody>
</table>

app/views/user_regions/new.html.erb
<div class="d-flex justify-content-center"><h1>Create User and Region</h1></div><br>
<%= form_with scope: :user_region, url: user_regions_path, local: true  do |f| %>

	<div class="form-group d-flex justify-content-center">
		<%= f.label :User , "User name:", class: "control-label col-md-3"%>
		<%= f.collection_select :user_id, User.all, :id, :name, {},{:class=>"form-control col-md-8"} %>
	</div>
	<div class="form-group d-flex justify-content-center">
		<%= f.label :Region , "Region:", class: "control-label col-md-3"%>
		<%= f.collection_select :region_id,Region.all, :id,:region_name, {}, {:class=>"form-control col-md-8"} %>
	</div>
	<div class="offset-md-5">
		<%= f.submit "Save", class: "btn btn-primary" %>
		<%= f.submit "Cancel", class: " btn btn-info" %>
		<%= link_to 'Back' ,  user_regions_path, class: " btn btn-success"%>
	</div>

<% end %> 

app/views/user_regions/show.html.erb
<div class="d-flex justify-content-center"><h1>Show User Region</h1></div><br>

<p>
	<strong>User:</strong>
	<%= @user_region.user.name %>
</p>
<p>
	<strong>Region:</strong>
	<%= @user_region.region.region_name %>
</p>
<div>
	<%= link_to 'Back' , user_regions_path, :class=> "btn btn-outline-danger"%>
</div> 